name: Release new version

on:
    workflow_dispatch:
        inputs:
            release_type:
                description: 'Release type'
                required: true
                type: choice
                options:
                    - major
                    - minor
                    - patch

jobs:
    prepare-release:
        if: github.event_name == 'workflow_dispatch'
        name: Prepare Release PR
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install node dependencies
              run: npm install

            - name: Compile Javascript App
              run: npm run build

            - name: Create version update branch
              id: create-branch
              run: |
                  BRANCH_NAME="update/$(date +%Y-%m-%d)/${{ github.event.inputs.release_type }}-release"
                  git checkout -b $BRANCH_NAME
                  echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT

            - name: Update version and changelog
              run: npm run update-version
              env:
                  RELEASE_TYPE: ${{ github.event.inputs.release_type }}

            - name: Commit changes
              run: |
                  git config user.name 'github-actions[bot]'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
                  git add .
                  git commit -m "Version bump & changelog update" --no-verify
                  git push --set-upstream origin ${{ steps.create-branch.outputs.BRANCH_NAME }}

            - name: Push changes and create Pull Request
              run: |
                  gh pr create --title "Release ${{ github.event.inputs.release_type }}" --body "Release ${{ github.event.inputs.release_type }}" --base trunk --head ${{ steps.create-branch.outputs.BRANCH_NAME }}
